mod utils;
pub mod ex00_adder;
pub mod ex01_multiplier;
pub mod ex02_gray_code;
pub mod ex03_eval_formula;
pub mod ex04_print_truth_table;
pub mod ex05_negation_normal_form;
mod ex06_conjunctive_normal_form;
mod ex07_sat;
mod ex08_powerset;
mod ex09_eval_set;
